version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hanouti_db
    restart: always
    environment:
      POSTGRES_USER: hanouti_user
      POSTGRES_PASSWORD: hanouti_password
      POSTGRES_DB: hanouti_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
