"""update_models_phase03

Revision ID: 58fa9f5c76d1
Revises: 
Create Date: 2025-11-21 01:46:00.809908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fa9f5c76d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('categories', 'color')
    op.drop_column('categories', 'icon')
    op.add_column('products', sa.Column('sku', sa.String(), nullable=True))
    op.add_column('products', sa.Column('purchase_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('stock_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('min_qty', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_column('products', 'stock')
    op.drop_column('products', 'min_stock')
    op.drop_column('products', 'image')
    op.drop_column('products', 'description')
    op.drop_column('products', 'cost')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('cost', sa.FLOAT(), nullable=True))
    op.add_column('products', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.add_column('products', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.add_column('products', sa.Column('min_stock', sa.INTEGER(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'image_url')
    op.drop_column('products', 'unit')
    op.drop_column('products', 'min_qty')
    op.drop_column('products', 'stock_qty')
    op.drop_column('products', 'sale_price')
    op.drop_column('products', 'purchase_price')
    op.drop_column('products', 'sku')
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(), nullable=True))
    op.add_column('categories', sa.Column('color', sa.VARCHAR(), nullable=True))
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
